version: '3.9'
services:
  mongo:
    image: mongo:6
    container_name: ecommerce_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: .
      dockerfile: api_ecommercePet/Dockerfile
    container_name: ecommerce_api
    environment:
      - MONGODB_URI=mongodb://mongo:27017/eCommercePet
      - PORT=3001
      - JWT_SECRET=troque-esta-string-super-secreta
    depends_on:
      - mongo
    ports:
      - "3001:3001"

  web:
    build:
      context: .
      dockerfile: front_react_ecommerce/Dockerfile
    container_name: ecommerce_web
    environment:
      - REACT_APP_API_BASE=http://localhost:3001
    depends_on:
      - api
    ports:
      - "3000:80"

volumes:
  mongo_data:
