# Dockerfile de desenvolvimento para o frontend
FROM node:18-alpine
WORKDIR /app

# Copia apenas manifestos para cache de dependências
COPY package*.json ./
RUN npm install

# Copia código (será sobreposto por volume, mas útil para build inicial)
COPY . .

ENV CHOKIDAR_USEPOLLING=true \
    NODE_ENV=development

EXPOSE 3000
CMD ["npm","start"]
